import type { RequestItem } from '@/entities/request/model'

export const requestsMockDb: RequestItem[] = [
  {
    id: '1',
    number: 'КС-0002',
    pharmacyCode: '065',
    pharmacyCity: 'Геленджик',
    pharmacyAddress: 'Островского 7',
    createdAt: '2025-07-20T12:35:45.000Z',
    priority: 'high',
    topic: 'Поломка кассы',
    category: 'Кассы',
    technician: null,
    reactionTime: '02:48',
    resolutionTime: null,
    status: 'new',
  },
  {
    id: '2',
    number: 'ХЛ-0002',
    pharmacyCode: '150',
    pharmacyCity: 'Кореновск',
    pharmacyAddress: 'Красная 108',
    createdAt: '2025-07-20T12:35:45.000Z',
    priority: 'medium',
    topic: 'Холодильник сильно гудит',
    category: 'Холодильники',
    technician: 'Федоровский Н.',
    reactionTime: '05:01',
    resolutionTime: '01:35:34',
    status: 'inProgress',
  },
  {
    id: '3',
    number: 'КН-0002',
    pharmacyCode: '045',
    pharmacyCity: 'Тимашевск',
    pharmacyAddress: 'Интернац 3Б',
    createdAt: '2025-07-20T12:35:45.000Z',
    priority: 'low',
    topic: 'Конденсат на внутреннем блоке',
    category: 'Кондиционеры',
    technician: 'Максимов П.',
    reactionTime: '05:01',
    resolutionTime: '02:30:17',
    status: 'done',
  },
  {
    id: '4',
    number: 'ИЭ-0002',
    pharmacyCode: '164',
    pharmacyCity: 'РНД',
    pharmacyAddress: 'Сельмаш 92',
    createdAt: '2025-07-20T12:35:45.000Z',
    priority: 'critical',
    topic: 'Нужно поверить гигрометр',
    category: 'Изм. оборуд.',
    technician: 'Алексеев М.',
    reactionTime: '05:01',
    resolutionTime: '02:30:17',
    status: 'done',
  },
  {
    id: '5',
    number: 'ПО-0002',
    pharmacyCode: '190',
    pharmacyCity: 'Геленджик',
    pharmacyAddress: 'Алуштинская 24',
    createdAt: '2025-07-20T12:35:45.000Z',
    priority: 'high',
    topic: 'Заметили крысу у входа',
    category: 'Помещения',
    technician: 'Сидоров Е.',
    reactionTime: '05:01',
    resolutionTime: '02:30:17',
    status: 'closed',
  },
]
