import type { RequestItem } from '@/entities/request/model'

function createMockDate(daysAgo: number, hours = 12, minutes = 0, seconds = 0): string {
  const now = new Date()
  const date = new Date(
    now.getFullYear(),
    now.getMonth(),
    now.getDate() - daysAgo,
    hours,
    minutes,
    seconds,
    0,
  )
  return date.toISOString()
}

export const requestsMockDb: RequestItem[] = [
  {
    id: '1',
    number: 'КС-0002',
    pharmacyCode: '065',
    pharmacyCity: 'Геленджик',
    pharmacyAddress: 'Островского 7',
    createdAt: createMockDate(0, 12, 35, 45), // сегодня
    priority: 'high',
    topic: 'Поломка кассы',
    category: 'Кассы',
    technician: null,
    reactionTime: null,
    reactionState: 'neutral',
    resolutionTime: null,
    resolutionState: 'neutral',
    status: 'new',
  },

  {
    id: '2',
    number: 'СК-0012',
    pharmacyCode: '201',
    pharmacyCity: 'Новороссийск',
    pharmacyAddress: 'Советов 31',
    createdAt: createMockDate(1, 12, 10, 45), // вчера
    priority: 'medium',
    topic: 'Сбой сканера штрих-кодов',
    category: 'ИТ',
    technician: 'Киселев А.',
    status: 'inProgress',
    reactionTime: '00:18:30',
    reactionState: 'ok',
    resolutionTime: '00:12:42',
    resolutionState: 'neutral',
  },

  {
    id: '3',
    number: 'ИТ-0003',
    pharmacyCode: '150',
    pharmacyCity: 'Сочи',
    pharmacyAddress: 'Ленина 12',
    createdAt: '2025-11-21T11:48:12.000Z',
    priority: 'high',
    topic: 'Проблемы с интернетом',
    category: 'ИТ',
    technician: 'Федоровский Н.',
    status: 'inProgress',
    reactionTime: '00:52:28',
    reactionState: 'ok',
    resolutionTime: '00:47:41',
    resolutionState: 'neutral',
  },

  {
    id: '4',
    number: 'СА-0002',
    pharmacyCode: '150',
    pharmacyCity: 'Кореновск',
    pharmacyAddress: 'Красная 108',
    createdAt: '2025-11-20T10:18:42.000Z',
    priority: 'medium',
    topic: 'Унитаз перестал смывать',
    category: 'Сантехника',
    technician: 'Малахов Н.',
    reactionTime: '00:29:59',
    reactionState: 'ok',
    resolutionTime: '02:30:17',
    resolutionState: 'breach',
    status: 'ready',
  },

  {
    id: '5',
    number: 'ИТ-0004',
    pharmacyCode: '164',
    pharmacyCity: 'Краснодар',
    pharmacyAddress: 'Трудовая 5',
    createdAt: '2025-11-19T09:10:00.000Z',
    priority: 'medium',
    topic: 'Не работает принтер',
    category: 'ИТ',
    technician: 'Алексеев М.',
    reactionTime: '00:21:00',
    reactionState: 'ok',
    resolutionTime: null,
    resolutionState: 'neutral',
    status: 'paused',
  },
  {
    id: '6',
    number: 'ПО-0002',
    pharmacyCode: '190',
    pharmacyCity: 'Геленджик',
    pharmacyAddress: 'Душистая 24',
    createdAt: '2025-11-17T16:35:45.000Z',
    priority: 'high',
    topic: 'Заметили крыс у входа',
    category: 'Помещения',
    technician: 'Сидоров Е.',
    reactionTime: '00:05:17',
    reactionState: 'ok',
    resolutionTime: '00:58:12',
    resolutionState: 'ok',
    status: 'closed',
  },
  {
    id: '7',
    number: 'ЭЛ-0004',
    pharmacyCode: '164',
    pharmacyCity: 'Краснодар',
    pharmacyAddress: 'Трудовая 5',
    createdAt: '2025-11-14T14:22:05.000Z',
    priority: 'high',
    topic: 'Искрит розетка',
    category: 'Электрика',
    technician: 'Малахов Н.',
    reactionTime: '00:55:12',
    reactionState: 'breach',
    resolutionTime: '00:48:03',
    resolutionState: 'ok',
    status: 'closed',
  },
  {
    id: '8',
    number: 'ХЛ-0002',
    pharmacyCode: '150',
    pharmacyCity: 'Кореновск',
    pharmacyAddress: 'Красная 108',
    createdAt: '2025-10-14T12:10:10.000Z',
    priority: 'medium',
    topic: 'Холодильник сильно гудит',
    category: 'Холодильники',
    technician: 'Федоровский Н.',
    reactionTime: '00:14:22',
    reactionState: 'ok',
    resolutionTime: null,
    resolutionState: 'neutral',
    status: 'awaitingParts',
  },
  {
    id: '9',
    number: 'КТ-0002',
    pharmacyCode: '065',
    pharmacyCity: 'Геленджик',
    pharmacyAddress: 'Островского 7',
    createdAt: '2025-06-26T10:30:17.000Z',
    priority: 'high',
    topic: 'Сломался кассовый терминал',
    category: 'Кассы',
    technician: 'Федоровский Н.',
    reactionTime: '00:16:00',
    reactionState: 'ok',
    resolutionTime: '01:15:00',
    resolutionState: 'ok',
    status: 'ready',
  },
  {
    id: '10',
    number: 'ИТ-0005',
    pharmacyCode: '267',
    pharmacyCity: 'Анапа',
    pharmacyAddress: 'Парковая 67к2',
    createdAt: '2025-02-14T10:35:45.000Z',
    priority: 'high',
    topic: 'Нужен новый компьютер',
    category: 'ИТ',
    technician: 'Китов Я.',
    reactionTime: '00:33:00',
    reactionState: 'breach',
    resolutionTime: null,
    resolutionState: 'neutral',
    status: 'awaitingParts',
  },
  {
    id: '11',
    number: 'ИЗ-0002',
    pharmacyCode: '164',
    pharmacyCity: 'РНД',
    pharmacyAddress: 'Сельмаш 92',
    createdAt: '2025-02-11T11:45:12.000Z',
    priority: 'critical',
    topic: 'Нужно поверить гигрометр',
    category: 'Изм. оборуд.',
    technician: 'Алексеев М.',
    reactionTime: '00:10:00',
    reactionState: 'ok',
    resolutionTime: '01:35:34',
    resolutionState: 'ok',
    status: 'ready',
  },
]
